### ISSUE TITLE
Implement wildcards for source files, and allow an array of patterns

### ISSUE THREAD

**Issue by gochinj** [noInfoPath/grunt-nodocs#1]
It would be a nice enhancement to support `gulp` style wildcard patterns, and allows user to supply an array of possibilities.  The paths should support a NOT capability to allows for the exclusion of files.

``` js
{
    src: ['/**/moose*.js', '/squirrel.html', '!/boris/*']
}
```

In the above example all files, in all subfolders, where the file name starts with moose and ends with js will be returned. Also, the file squirrel.html will be returned, nothing below the boris folder will be returned.

**Comment by ryeguyimg** [comment]
Grunt has this functionality built in. I have implemented it and tested with most scenarios.
