### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by russellmurray** [noInfoPath/grunt-nodocs#2]
I noticed some spelling errors in your documentation.

Check the Default Code Sample section, the word function is misspelled as fucntion

**Comment by ryeguyimg** [comment]
Thanks for the heads up. I too have noticed some mistakes in grammar and spelling and will be updating the documentation in the next release. 

Didn't want to keep making new releases for just grammar edits.

If anyone has any questions about something there, please don't hesitate to reply to this issue.

Rye

**Comment by ryeguyimg** [comment]
Spelling and grammar mistakes have been fixed.
